baseURL = "https://smoqadam.me/"
languageCode = "en-us"
title = "Saeed's Blog"
theme = "hugo_theme_pickles"
contentdir = "content"
publishdir = "public"


[params]
  paginate = 10
  twitter = "SMoghadamzadeh"
  github = "smoqadam"
  linkedin = "saeedmoqadam"
  # Google Analytics API key.
  # ga_api_key = "Your Google Analytics tracking id"


[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
pattern = "2017"
