# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 138.197.141.221
          username: root
          port: 22
          key: ${{secrets.SERVER}}
          script: |
            cd /var/www/html/blog
            eval "$(ssh-agent -s)"
            ssh-add /root/.ssh/github
            git pull origin main
            hugo
